version: '3.8'

services:
  db:
    image: mysql:8
    container_name: finanzapp_db
    restart: always
    environment:
      MYSQL_DATABASE: finanzapp
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: finanzapp_app
    restart: always
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      PORT: 8181
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: secret
      DB_NAME: finanzapp
      JWT_SECRET: clave_secreta
    volumes:
      - ./templates:/app/templates
    working_dir: /app
    command: ["./finanzapp"]

volumes:
  db_data:
